# Generated by Django 5.2.4 on 2025-07-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_todo_created_at_alter_todo_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
